jobs:
  include:
    - stage: Run tests
      language: java
      script : mvn test
    - stage: Deploy staging
      language: java
      deploy:
        provider: heroku
        api_key: $HEROKU_API
        app: spring-demi-integracion-stagin
        on:
          branch: main
    - stage: Ping staging
      script: 'curl https://spring-demi-integracion-stagin.herokuapp.com/v1/prueba'
    - stage: Deploy
      language: java
      deploy:
        provider: heroku
        api_key: $HEROKU_API
        app: spring-demo-integracion
        on:
            branch: main
    - stage: Ping production
      script: 'curl https://spring-demo-integracion.herokuapp.com/v1/prueba'