language: java
script:
  - mvn test
deploy:
  provider: heroku
  api_key: bP/n65ii0Gn3gJe6X6uuIxTrppBdy5UeAsQSeCAWh7LkYLakkS7/ijGYTXh7MkYU8ubMG1KTrnLbDry0FEKdIvGpIEqDTqJ0WLlxeKRzwy9sU1tmWbkVRTbuiB2LOIreN4u/iaSUXuIhcpgk+65hGYN85qNzmSyOomvyHBW6V2lN7nY34Uj0ADeZbV9o/RtnzhHgvozC7a1XRqmMsjWvpH48SulPUQpPLvOZaRtJE5FCjxvRjx8TqP9GeJt9lByGNJJfvpjPjEzO9QpbQXtbikZrK1kGy/QaygsBeAg+D5awF8ffVRnfZ/zbBsoIF66Do10eR1SIxPbA374wHgWQlCM5rCjdTDm6wpREEJpEV1imzxwweG5tumujXQtcxT4STRektBTOVJ/9WGdB3S9ZHHokev3xQp/7Y34lXVI4ThlpYaxj6oIk3yut5CXYP+KwQZ+MfKhhDmhCksHI/JPwNERq/MREVNwzWebmRQ821AHfzAXsEu96WkxgDCl5nK/8qkJ0HQLTuMr4In7swOPEv7p0a+S+wNEPNWAhu1DP+c2mXlZlaXjSVPqD5DlVtouFdpghTn5EErSWfAmzSs0fSYmJn3l4YZeEwCX7ZRlxl3Z8Sxi16A27H3Bxh9rR7mENa+8dzvMu+2+ccwYjUAv48olYqkOm2HgnaXKyaTDQKuw=
  app: spring-demo-integracion
  branch: main